version: "3"

services:
  node:
    container_name: simdnode0
    image: "cosmossdk/simd"
    environment:
      - DEBUG=1
      - ID=0
      - LOG=${LOG:-simd.log}
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
    volumes:
      - ./.testnets:/data:Z
      - ./internal:/internal:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/25
