version: "3"

services:
  mongodb:
    container_name: mongo_server
    image: "mongo:latest"
    restart: always
    networks:
      localnet:
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb:/data/db
