name: Lint
#  Lint workflow checks lint issues
#  This workflow run on workflow_dispatch & on every pull request
on:
  pull_request:
  workflow_dispatch:

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: marian-code/python-lint-annotate@v3
        with:
          # extra-pycodestyle-options: "--rcfile="
          use-pylint: true
          python-version: "3.8"
