name: Upgrade Test
#  Upgrade Test workflow tests software upgrade
#  This workflow run on pushes to master, workflow_dispatch & on every pull request
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test-upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test software upgrade
        run: |
          make test-upgrade
        env:
          IS_PUBLIC: false
